/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type AiChatTransformer from '#transformers/ai_chat_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type AiChat = InferData<AiChatTransformer>
  export namespace AiChat {
    export type Variants = InferVariants<AiChatTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
