/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AiAgentConfirmationSchema extends BaseModel {
  static $columns = [
    'action',
    'agentRunId',
    'assistantMessageId',
    'confirmedAt',
    'confirmedByUserId',
    'conversationId',
    'createdAt',
    'executionStartedAt',
    'executionToken',
    'expiresAt',
    'id',
    'payload',
    'requestedByUserId',
    'status',
    'targetId',
    'targetSummary',
    'targetType',
    'updatedAt',
  ] as const
  $columns = AiAgentConfirmationSchema.$columns
  @column()
  declare action: string
  @column()
  declare agentRunId: string
  @column()
  declare assistantMessageId: number | null
  @column.dateTime()
  declare confirmedAt: DateTime | null
  @column()
  declare confirmedByUserId: number | null
  @column()
  declare conversationId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare executionStartedAt: DateTime | null
  @column()
  declare executionToken: string | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare payload: any
  @column()
  declare requestedByUserId: number
  @column()
  declare status: string
  @column()
  declare targetId: string | null
  @column()
  declare targetSummary: any | null
  @column()
  declare targetType: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AiAgentPendingQuerySchema extends BaseModel {
  static $columns = [
    'completedAt',
    'conversationId',
    'createdAt',
    'expiresAt',
    'id',
    'params',
    'requestedByUserId',
    'status',
    'templateCode',
    'templateVersion',
    'updatedAt',
  ] as const
  $columns = AiAgentPendingQuerySchema.$columns
  @column.dateTime()
  declare completedAt: DateTime | null
  @column()
  declare conversationId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare params: any
  @column()
  declare requestedByUserId: number
  @column()
  declare status: string
  @column()
  declare templateCode: string
  @column()
  declare templateVersion: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AiChatConversationSchema extends BaseModel {
  static $columns = ['contextSummary', 'createdAt', 'id', 'title', 'updatedAt', 'userId'] as const
  $columns = AiChatConversationSchema.$columns
  @column()
  declare contextSummary: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class AiChatMessageSchema extends BaseModel {
  static $columns = [
    'citations',
    'content',
    'conversationId',
    'createdAt',
    'id',
    'role',
    'runtimeDetails',
    'updatedAt',
  ] as const
  $columns = AiChatMessageSchema.$columns
  @column()
  declare citations: any
  @column()
  declare content: string
  @column()
  declare conversationId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare role: string
  @column()
  declare runtimeDetails: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ApiKeySchema extends BaseModel {
  static $columns = [
    'createdAt',
    'expiresAt',
    'id',
    'keyHash',
    'lastUsedAt',
    'name',
    'prefix',
    'revokedAt',
    'updatedAt',
  ] as const
  $columns = ApiKeySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare keyHash: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare prefix: string
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AuditLogSchema extends BaseModel {
  static $columns = [
    'action',
    'actorUserId',
    'createdAt',
    'id',
    'ipAddress',
    'metadata',
    'requestId',
    'targetId',
    'targetType',
    'userAgent',
  ] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorUserId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string | null
  @column()
  declare metadata: any | null
  @column()
  declare requestId: string | null
  @column()
  declare targetId: string | null
  @column()
  declare targetType: string
  @column()
  declare userAgent: string | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ChannelBindingChallengeSchema extends BaseModel {
  static $columns = [
    'channel',
    'codeHash',
    'createdAt',
    'expiresAt',
    'externalTenantId',
    'externalUserId',
    'id',
    'usedAt',
  ] as const
  $columns = ChannelBindingChallengeSchema.$columns
  @column()
  declare channel: string
  @column()
  declare codeHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare externalTenantId: string
  @column()
  declare externalUserId: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare usedAt: DateTime | null
}

export class ChannelConversationSchema extends BaseModel {
  static $columns = [
    'channel',
    'conversationId',
    'createdAt',
    'externalConversationKey',
    'externalTenantId',
    'id',
    'updatedAt',
    'userId',
  ] as const
  $columns = ChannelConversationSchema.$columns
  @column()
  declare channel: string
  @column()
  declare conversationId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare externalConversationKey: string
  @column()
  declare externalTenantId: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class ChannelIdentitySchema extends BaseModel {
  static $columns = [
    'boundAt',
    'channel',
    'createdAt',
    'externalTenantId',
    'externalUserId',
    'id',
    'revokedAt',
    'status',
    'updatedAt',
    'userId',
  ] as const
  $columns = ChannelIdentitySchema.$columns
  @column.dateTime()
  declare boundAt: DateTime
  @column()
  declare channel: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare externalTenantId: string
  @column()
  declare externalUserId: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class GithubIdentitySchema extends BaseModel {
  static $columns = ['createdAt', 'githubId', 'githubLogin', 'id', 'updatedAt', 'userId'] as const
  $columns = GithubIdentitySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare githubId: bigint | number
  @column()
  declare githubLogin: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class GithubLinkStateSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'stateHash', 'usedAt', 'userId'] as const
  $columns = GithubLinkStateSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare stateHash: string
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userId: number
}

export class GithubLoginChallengeSchema extends BaseModel {
  static $columns = [
    'codeHash',
    'createdAt',
    'expiresAt',
    'githubEmail',
    'githubId',
    'githubLogin',
    'id',
    'usedAt',
  ] as const
  $columns = GithubLoginChallengeSchema.$columns
  @column()
  declare codeHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare githubEmail: string
  @column()
  declare githubId: bigint | number
  @column()
  declare githubLogin: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare usedAt: DateTime | null
}

export class GithubLoginExchangeSchema extends BaseModel {
  static $columns = ['codeHash', 'createdAt', 'expiresAt', 'id', 'usedAt', 'userId'] as const
  $columns = GithubLoginExchangeSchema.$columns
  @column()
  declare codeHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userId: number
}

export class KnowledgeChunkSchema extends BaseModel {
  static $columns = [
    'chunkIndex',
    'content',
    'createdAt',
    'documentId',
    'embedding',
    'embeddingModel',
    'id',
  ] as const
  $columns = KnowledgeChunkSchema.$columns
  @column()
  declare chunkIndex: number
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare documentId: bigint | number
  @column()
  declare embedding: any
  @column()
  declare embeddingModel: string
  @column({ isPrimary: true })
  declare id: bigint | number
}

export class KnowledgeDocumentRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'documentId', 'roleId'] as const
  $columns = KnowledgeDocumentRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare documentId: bigint | number
  @column()
  declare roleId: number
}

export class KnowledgeDocumentSchema extends BaseModel {
  static $columns = [
    'content',
    'contentHash',
    'createdAt',
    'id',
    'requiredPermission',
    'title',
    'updatedAt',
  ] as const
  $columns = KnowledgeDocumentSchema.$columns
  @column()
  declare content: string
  @column()
  declare contentHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare requiredPermission: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class LlmConfigurationSchema extends BaseModel {
  static $columns = [
    'chatApiKey',
    'chatBaseUrl',
    'chatModel',
    'createdAt',
    'embeddingApiKey',
    'embeddingBaseUrl',
    'embeddingDimensions',
    'embeddingModel',
    'id',
    'requestTimeoutMs',
    'updatedAt',
    'wecomBotId',
    'wecomBotSecret',
    'wecomBotTenantId',
    'wecomBotWsUrl',
  ] as const
  $columns = LlmConfigurationSchema.$columns
  @column()
  declare chatApiKey: string | null
  @column()
  declare chatBaseUrl: string | null
  @column()
  declare chatModel: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare embeddingApiKey: string | null
  @column()
  declare embeddingBaseUrl: string | null
  @column()
  declare embeddingDimensions: number
  @column()
  declare embeddingModel: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare requestTimeoutMs: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare wecomBotId: string | null
  @column()
  declare wecomBotSecret: string | null
  @column()
  declare wecomBotTenantId: string | null
  @column()
  declare wecomBotWsUrl: string | null
}

export class PermissionSchema extends BaseModel {
  static $columns = [
    'code',
    'createdAt',
    'description',
    'groupName',
    'id',
    'isSystem',
    'name',
    'updatedAt',
  ] as const
  $columns = PermissionSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare groupName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isSystem: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RolePermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'permissionId', 'roleId'] as const
  $columns = RolePermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare permissionId: number
  @column({ isPrimary: true })
  declare roleId: number
}

export class RoleSchema extends BaseModel {
  static $columns = [
    'code',
    'createdAt',
    'description',
    'id',
    'isSystem',
    'name',
    'updatedAt',
  ] as const
  $columns = RoleSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isSystem: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'roleId', 'userId'] as const
  $columns = UserRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare roleId: number
  @column({ isPrimary: true })
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'disabledAt',
    'email',
    'failedLoginAttempts',
    'fullName',
    'id',
    'lockedUntil',
    'password',
    'passwordChangedAt',
    'twoFactorEnabled',
    'twoFactorRecoveryCodes',
    'twoFactorSecret',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare disabledAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare failedLoginAttempts: number
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lockedUntil: DateTime | null
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime()
  declare passwordChangedAt: DateTime | null
  @column()
  declare twoFactorEnabled: boolean
  @column()
  declare twoFactorRecoveryCodes: string | null
  @column()
  declare twoFactorSecret: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WecomMessageTemplateSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'description',
    'enabled',
    'id',
    'msgtype',
    'name',
    'parameters',
    'payload',
    'updatedAt',
    'webhookUrl',
  ] as const
  $columns = WecomMessageTemplateSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare enabled: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare msgtype: string
  @column()
  declare name: string
  @column()
  declare parameters: any
  @column()
  declare payload: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare webhookUrl: string
}
