/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AiChatConversationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'title', 'updatedAt', 'userId'] as const
  $columns = AiChatConversationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class AiChatMessageSchema extends BaseModel {
  static $columns = ['content', 'conversationId', 'createdAt', 'id', 'role', 'updatedAt'] as const
  $columns = AiChatMessageSchema.$columns
  @column()
  declare content: string
  @column()
  declare conversationId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ApiKeySchema extends BaseModel {
  static $columns = [
    'createdAt',
    'expiresAt',
    'id',
    'keyEncrypted',
    'keyHash',
    'lastUsedAt',
    'name',
    'prefix',
    'revokedAt',
    'scopes',
    'systemCodes',
    'updatedAt',
  ] as const
  $columns = ApiKeySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare keyEncrypted: string | null
  @column()
  declare keyHash: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare prefix: string
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare scopes: any | null
  @column()
  declare systemCodes: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AuditLogSchema extends BaseModel {
  static $columns = [
    'action',
    'actorUserId',
    'createdAt',
    'id',
    'ipAddress',
    'metadata',
    'requestId',
    'targetId',
    'targetType',
    'userAgent',
  ] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorUserId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string | null
  @column()
  declare metadata: any | null
  @column()
  declare requestId: string | null
  @column()
  declare targetId: string | null
  @column()
  declare targetType: string
  @column()
  declare userAgent: string | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EmbeddingSnapshotItemSchema extends BaseModel {
  static $columns = [
    'contentHash',
    'embeddedContent',
    'embedding',
    'id',
    'menuItemId',
    'snapshotId',
  ] as const
  $columns = EmbeddingSnapshotItemSchema.$columns
  @column()
  declare contentHash: string
  @column()
  declare embeddedContent: string
  @column()
  declare embedding: any
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare menuItemId: string
  @column()
  declare snapshotId: string
}

export class EmbeddingSnapshotSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'description',
    'errorMessage',
    'finishedAt',
    'id',
    'isCurrent',
    'itemCount',
    'itemsEmbedded',
    'itemsTotal',
    'label',
    'startedAt',
    'status',
    'syncLogId',
    'systemId',
    'version',
  ] as const
  $columns = EmbeddingSnapshotSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare errorMessage: string | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isCurrent: boolean
  @column()
  declare itemCount: number
  @column()
  declare itemsEmbedded: number
  @column()
  declare itemsTotal: number
  @column()
  declare label: string | null
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare syncLogId: string | null
  @column()
  declare systemId: string
  @column()
  declare version: number
}

export class MenuEmbeddingSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'embeddedAt',
    'embeddedContent',
    'embedding',
    'id',
    'menuItemId',
    'updatedAt',
  ] as const
  $columns = MenuEmbeddingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare embeddedAt: DateTime
  @column()
  declare embeddedContent: string
  @column()
  declare embedding: any
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare menuItemId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MenuItemSchema extends BaseModel {
  static $columns = [
    'contentHash',
    'createdAt',
    'description',
    'externalUrl',
    'icon',
    'id',
    'isActive',
    'keywords',
    'metadata',
    'name',
    'parentId',
    'path',
    'route',
    'sortOrder',
    'systemId',
    'updatedAt',
  ] as const
  $columns = MenuItemSchema.$columns
  @column()
  declare contentHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare externalUrl: string | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare keywords: string | null
  @column()
  declare metadata: any | null
  @column()
  declare name: string
  @column()
  declare parentId: string | null
  @column()
  declare path: string
  @column()
  declare route: string | null
  @column()
  declare sortOrder: number
  @column()
  declare systemId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NavigationDebugConversationSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'systemCode',
    'systemId',
    'title',
    'updatedAt',
    'userId',
  ] as const
  $columns = NavigationDebugConversationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare systemCode: string | null
  @column()
  declare systemId: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class NavigationDebugHistorySchema extends BaseModel {
  static $columns = [
    'conversationId',
    'createdAt',
    'durationMs',
    'errorMessage',
    'httpStatus',
    'id',
    'includeExplanation',
    'query',
    'response',
    'systemCode',
    'systemId',
    'topK',
    'userId',
  ] as const
  $columns = NavigationDebugHistorySchema.$columns
  @column()
  declare conversationId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationMs: number | null
  @column()
  declare errorMessage: string | null
  @column()
  declare httpStatus: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare includeExplanation: boolean | null
  @column()
  declare query: string
  @column()
  declare response: any | null
  @column()
  declare systemCode: string | null
  @column()
  declare systemId: string | null
  @column()
  declare topK: number | null
  @column()
  declare userId: number
}

export class PermissionSchema extends BaseModel {
  static $columns = [
    'code',
    'createdAt',
    'description',
    'groupName',
    'id',
    'isSystem',
    'name',
    'updatedAt',
  ] as const
  $columns = PermissionSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare groupName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isSystem: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RolePermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'permissionId', 'roleId'] as const
  $columns = RolePermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare permissionId: number
  @column({ isPrimary: true })
  declare roleId: number
}

export class RoleSchema extends BaseModel {
  static $columns = [
    'code',
    'createdAt',
    'description',
    'id',
    'isSystem',
    'name',
    'updatedAt',
  ] as const
  $columns = RoleSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isSystem: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SystemSchema extends BaseModel {
  static $columns = [
    'baseUrl',
    'code',
    'createdAt',
    'description',
    'id',
    'isActive',
    'metadata',
    'name',
    'updatedAt',
  ] as const
  $columns = SystemSchema.$columns
  @column()
  declare baseUrl: string
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare metadata: any | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'roleId', 'userId'] as const
  $columns = UserRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare roleId: number
  @column({ isPrimary: true })
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'failedLoginAttempts',
    'fullName',
    'id',
    'lockedUntil',
    'password',
    'passwordChangedAt',
    'twoFactorEnabled',
    'twoFactorRecoveryCodes',
    'twoFactorSecret',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare failedLoginAttempts: number
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lockedUntil: DateTime | null
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime()
  declare passwordChangedAt: DateTime | null
  @column()
  declare twoFactorEnabled: boolean
  @column()
  declare twoFactorRecoveryCodes: string | null
  @column()
  declare twoFactorSecret: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
