/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  AiChat: () => import('#controllers/ai_chat_controller'),
  ApiKeys: () => import('#controllers/api_keys_controller'),
  AuditLogs: () => import('#controllers/audit_logs_controller'),
  GithubOauth: () => import('#controllers/github_oauth_controller'),
  KnowledgeDocuments: () => import('#controllers/knowledge_documents_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Permissions: () => import('#controllers/permissions_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Roles: () => import('#controllers/roles_controller'),
  SystemStatus: () => import('#controllers/system_status_controller'),
  TwoFactorAuth: () => import('#controllers/two_factor_auth_controller'),
  Users: () => import('#controllers/users_controller'),
  WecomMessageTemplates: () => import('#controllers/wecom_message_templates_controller'),
}
