/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  ApiKeys: () => import('#controllers/api_keys_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  TwoFactorAuth: () => import('#controllers/two_factor_auth_controller'),
}
