/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddFieldButton: typeof import('./components/json-schema/components/AddFieldButton.vue')['default']
    AiChatApprovalCard: typeof import('./components/ai-chat/AiChatApprovalCard.vue')['default']
    AiChatAssistant: typeof import('./components/ai-chat/AiChatAssistant.vue')['default']
    AiChatCredentialCard: typeof import('./components/ai-chat/AiChatCredentialCard.vue')['default']
    AiChatMessageItem: typeof import('./components/ai-chat/AiChatMessageItem.vue')['default']
    AiMessageContent: typeof import('./components/ai-chat/AiMessageContent.vue')['default']
    AnalyticsPageTemplate: typeof import('./components/templates/AnalyticsPageTemplate.vue')['default']
    ApiKeyForm: typeof import('./components/workbench/ApiKeyForm.vue')['default']
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    ArrayEditor: typeof import('./components/json-schema/components/types/ArrayEditor.vue')['default']
    BooleanEditor: typeof import('./components/json-schema/components/types/BooleanEditor.vue')['default']
    CardPageShell: typeof import('./components/common/CardPageShell.vue')['default']
    CodeEditor: typeof import('./components/common/CodeEditor.vue')['default']
    ConfirmDialog: typeof import('./components/common/ConfirmDialog.vue')['default']
    DashboardPageTemplate: typeof import('./components/templates/DashboardPageTemplate.vue')['default']
    DataTable: typeof import('./components/common/DataTable.vue')['default']
    DescriptionActionRow: typeof import('./components/common/DescriptionActionRow.vue')['default']
    DetailPageTemplate: typeof import('./components/templates/DetailPageTemplate.vue')['default']
    ErrorBoundary: typeof import('./components/common/ErrorBoundary.vue')['default']
    FormDialogContent: typeof import('./components/common/FormDialogContent.vue')['default']
    FormDialogFooter: typeof import('./components/common/FormDialogFooter.vue')['default']
    JsonSchemaEditor: typeof import('./components/json-schema/components/JsonSchemaEditor.vue')['default']
    JsonSchemaVisualizer: typeof import('./components/json-schema/components/JsonSchemaVisualizer.vue')['default']
    JsonValidator: typeof import('./components/json-schema/features/JsonValidator.vue')['default']
    ListPage: typeof import('./components/common/ListPage.vue')['default']
    ManagedUserDialog: typeof import('./components/access-control/ManagedUserDialog.vue')['default']
    MessageScroller: typeof import('./components/ui/message-scroller/MessageScroller.vue')['default']
    MessageScrollerButton: typeof import('./components/ui/message-scroller/MessageScrollerButton.vue')['default']
    MessageScrollerContent: typeof import('./components/ui/message-scroller/MessageScrollerContent.vue')['default']
    MessageScrollerItem: typeof import('./components/ui/message-scroller/MessageScrollerItem.vue')['default']
    MessageScrollerProvider: typeof import('./components/ui/message-scroller/MessageScrollerProvider.vue')['default']
    MessageScrollerViewport: typeof import('./components/ui/message-scroller/MessageScrollerViewport.vue')['default']
    NavMain: typeof import('./components/NavMain.vue')['default']
    NavUser: typeof import('./components/NavUser.vue')['default']
    NumberEditor: typeof import('./components/json-schema/components/types/NumberEditor.vue')['default']
    ObjectEditor: typeof import('./components/json-schema/components/types/ObjectEditor.vue')['default']
    PageHeader: typeof import('./components/common/PageHeader.vue')['default']
    PageShell: typeof import('./components/common/PageShell.vue')['default']
    PasswordStrength: typeof import('./components/PasswordStrength.vue')['default']
    PermissionDialog: typeof import('./components/access-control/PermissionDialog.vue')['default']
    PermissionRolesPopover: typeof import('./components/access-control/PermissionRolesPopover.vue')['default']
    PermissionTransfer: typeof import('./components/common/PermissionTransfer.vue')['default']
    RoleDialog: typeof import('./components/access-control/RoleDialog.vue')['default']
    RolePermissionsPopover: typeof import('./components/access-control/RolePermissionsPopover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaFieldList: typeof import('./components/json-schema/components/SchemaFieldList.vue')['default']
    SchemaPropertyEditor: typeof import('./components/json-schema/components/SchemaPropertyEditor.vue')['default']
    SchemaTypeSelector: typeof import('./components/json-schema/components/SchemaTypeSelector.vue')['default']
    SchemaVisualEditor: typeof import('./components/json-schema/components/SchemaVisualEditor.vue')['default']
    SegmentedCodeInput: typeof import('./components/common/SegmentedCodeInput.vue')['default']
    SettingsPageTemplate: typeof import('./components/templates/SettingsPageTemplate.vue')['default']
    SiteHeader: typeof import('./components/SiteHeader.vue')['default']
    SqlEditor: typeof import('./components/common/SqlEditor.vue')['default']
    StringEditor: typeof import('./components/json-schema/components/types/StringEditor.vue')['default']
    TurnstileWidget: typeof import('./components/common/TurnstileWidget.vue')['default']
    TypeDropdown: typeof import('./components/json-schema/components/TypeDropdown.vue')['default']
    TypeEditor: typeof import('./components/json-schema/components/TypeEditor.vue')['default']
    WizardPageTemplate: typeof import('./components/templates/WizardPageTemplate.vue')['default']
    WorkflowPageTemplate: typeof import('./components/templates/WorkflowPageTemplate.vue')['default']
  }
}
