/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddFieldButton: typeof import('./components/json-schema/components/AddFieldButton.vue')['default']
    AiChatAssistant: typeof import('./components/AiChatAssistant.vue')['default']
    AiMessageContent: typeof import('./components/ai-chat/AiMessageContent.vue')['default']
    ApiKeyForm: typeof import('./components/workbench/ApiKeyForm.vue')['default']
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    ArrayEditor: typeof import('./components/json-schema/components/types/ArrayEditor.vue')['default']
    BooleanEditor: typeof import('./components/json-schema/components/types/BooleanEditor.vue')['default']
    CardPageShell: typeof import('./components/common/CardPageShell.vue')['default']
    ConfirmDialog: typeof import('./components/common/ConfirmDialog.vue')['default']
    DataTable: typeof import('./components/common/DataTable.vue')['default']
    DescriptionActionRow: typeof import('./components/common/DescriptionActionRow.vue')['default']
    FormDialogContent: typeof import('./components/common/FormDialogContent.vue')['default']
    FormDialogFooter: typeof import('./components/common/FormDialogFooter.vue')['default']
    JsonSchemaEditor: typeof import('./components/json-schema/components/JsonSchemaEditor.vue')['default']
    JsonSchemaVisualizer: typeof import('./components/json-schema/components/JsonSchemaVisualizer.vue')['default']
    JsonValidator: typeof import('./components/json-schema/features/JsonValidator.vue')['default']
    ManagementListPage: typeof import('./components/common/ManagementListPage.vue')['default']
    NavMain: typeof import('./components/NavMain.vue')['default']
    NavUser: typeof import('./components/NavUser.vue')['default']
    NumberEditor: typeof import('./components/json-schema/components/types/NumberEditor.vue')['default']
    ObjectEditor: typeof import('./components/json-schema/components/types/ObjectEditor.vue')['default']
    PasswordStrength: typeof import('./components/PasswordStrength.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaFieldList: typeof import('./components/json-schema/components/SchemaFieldList.vue')['default']
    SchemaPropertyEditor: typeof import('./components/json-schema/components/SchemaPropertyEditor.vue')['default']
    SchemaTypeSelector: typeof import('./components/json-schema/components/SchemaTypeSelector.vue')['default']
    SchemaVisualEditor: typeof import('./components/json-schema/components/SchemaVisualEditor.vue')['default']
    SegmentedCodeInput: typeof import('./components/common/SegmentedCodeInput.vue')['default']
    SiteHeader: typeof import('./components/SiteHeader.vue')['default']
    StringEditor: typeof import('./components/json-schema/components/types/StringEditor.vue')['default']
    TypeDropdown: typeof import('./components/json-schema/components/TypeDropdown.vue')['default']
    TypeEditor: typeof import('./components/json-schema/components/TypeEditor.vue')['default']
  }
}
